## Indexes

In [23]:
import pandas as pd

In [24]:
customers = {
    "firstname":["Sam","Tom","Phil"],
    "lastname":["johnson","Denis","Alli"],
    "email":["SamJ123@gmail.com","Tom_Den65@yahoo.com","Phil_Alli202@gmail.com"]
}


customers_df=pd.DataFrame(customers)
customers_df
#  the first column with numbers and no column name is called the index

  firstname lastname                   email
0       Sam  johnson       SamJ123@gmail.com
1       Tom    Denis     Tom_Den65@yahoo.com
2      Phil     Alli  Phil_Alli202@gmail.com

In [25]:
customers_df.email

0         SamJ123@gmail.com
1       Tom_Den65@yahoo.com
2    Phil_Alli202@gmail.com
Name: email, dtype: object

In [26]:
#  change the index
customers_df.set_index("email",inplace=True) 
# inplace = False is used to display the change but does not change the actual dataframe

In [27]:
customers_df

                       firstname lastname
email
SamJ123@gmail.com            Sam  johnson
Tom_Den65@yahoo.com          Tom    Denis
Phil_Alli202@gmail.com      Phil     Alli

In [28]:
# if u want to reset your index back to the default
customers_df.reset_index(inplace=True)

In [29]:
customers_df

                    email firstname lastname
0       SamJ123@gmail.com       Sam  johnson
1     Tom_Den65@yahoo.com       Tom    Denis
2  Phil_Alli202@gmail.com      Phil     Alli

#### Now using the stackoverlfow data

In [30]:
df = pd.read_csv("data/survey_results_public.csv")

In [32]:
df.head(4)

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
1,2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
2,3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
3,4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4

In [35]:
# lets change the index to the MainBranch column as it already has an id
df.set_index("MainBranch",inplace=True)

In [36]:
# now the MainBranch will be the index
df.head(5)

,Respondent,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
MainBranch,,,,,,,,,,,,,,,,,,,,,
I am a developer by profession,1,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
I am a developer by profession,2,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
I code primarily as a hobby,3,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
I am a developer by profession,4,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
"I used to be a developer by profession, but no longer am",5,Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8